### ISSUE TITLE
Would you consider merging the eredis and eredis_cluster packages?

### ISSUE THREAD

**Issue by ankhers** [Nordix/eredis_cluster#55]
A bit of background information. Currently at $DAYJOB we have our developers build against a single instance of redis, then we deploy against a cluster. This has lead to some confusion in the past about how things work. Would you be willing to merge the functionality of the two packages and have the driver decide what to do if redis is clustered vs single instance? Another option would be to have an option on connect say whether or not it should be in clustered mode.

If this is something you would be interested in, I would be more than happy to send a PR for whichever option you would prefer.

**Comment by zuiderkwast** [comment]
Added a note about cluster mode in the eredis README file with a link to eredis_cluster. Closing this.
