### ISSUE TITLE
Behavior when redis-server disappears without closing TCP connection

### ISSUE THREAD

**Issue by e-kmisk** [Nordix/eredis_cluster#59]
Hi,

We are working on an Ericsson application that uses this module, and noticed something odd when doing HA testing on a redis cluster.

# Setup
6 redis masters, 6 redis replicas, one (non-distributed) erlang application using eredis_cluster, connected to the 6 masters.
We were testing failovers from master => replica.

# Graceful termination of redis master
When we "gracefully" terminate a redis master (in our case with SIGTERM via `kubectl delete`), the TCP connections between  `eredis <=> redis-server` get closed explicitly (via a TCP RST?). When this happens, for a short period the eredis client components seem to try to reconnect, but the logs stop after that period, and the replica who became the master is contacted. 

Example of related logs:
```
=ERROR REPORT==== ?-Apr-????::19:00:02.729171 ===
eredis: Re-establishing connection to "192.168.25.92":6379 due to tcp_closed

=ERROR REPORT==== ?-Apr-????::19:00:02.729247 ===
eredis: Re-establishing connection to "192.168.25.92":6379 due to tcp_closed

#############  ^ repeated a few times ...

=ERROR REPORT==== ?-Apr-????::19:00:02.729520 ===
eredis: Re-establishing connection to "192.168.25.92":6379 due to tcp_closed

#############  afterwards a new process comes online (the IP address is the new masters'):

=PROGRESS REPORT==== ?-Apr-????::19:00:32.784499 ===
    supervisor: {local,eredis_cluster_pool}
    started: [{pid,<0.7509.24>},
              {id,'192.168.232.127#6379'},
              {mfargs,{poolboy,start_link,
                               [[{name,{local,'192.168.232.127#6379'}},
                                 {worker_module,eredis},
                                 {size,10},
                                 {max_overflow,0}],
                                [{host,"192.168.232.127"},{port,6379}]]}},
              {restart_type,permanent},
              {shutdown,5000},
              {child_type,worker}]
```

Following this:

* ✔ normal cluster operations are resumed, ie. requests go to the new master, and the TCP connection to the old node is severed at the kernel level (not completely sure that all resources related to old master are freed however)
* ✔queries towards the dead/dying redis master seem to get queued and eventually sent to the new master, so the failover is transparent to the caller, aside from increased latency

# Forceful/brutal termination of redis master
If we destroy the target redis-server in a way to emulate a hardware failure where no TCP reset packet is sent out from the server and it is killed instantly (in our case using `kubectl delete --force --grace-period=0`), then
- ✔ the redis clustering side seems to work as expected - after a short timeout (NODE_TIMEOUT?) the replica overtakes the master role as the redis cluster agrees that the old master is dead
- ❌ the eredis client side seems to get into a broken state:
   - TCP connections towards the `<IP address>:<port>` of the killed redis-server remains `ESTABLISHED` indefinitely according to `/proc/net/tcp`
   - connection towards the new master (previously replica) is never set up (unlike in the graceful scenario), implying that the shard mappings are not refreshed
   - there are some `{error, etimedout}` messages sent to erlang processes' message queue who invoked eredis_cluser functions (trying to query from shards which were on that master) - these messages are unexpected/unhandled in the callers

#  Question

Could you clarify what would be the expected behavior from `eredis_cluser` (and maybe `eredis`) for the Forceful/brutal termination scenario? Is this a bug or is there maybe some configuration tweak we are unaware of?

From the module user's perspective we would expect it to work very similarly to the 1st scenario:
* after some configurable(?) timeout with no incoming packets (read timeout), the socket and the erlang processes related to it should react similarly as in the explicit `tcp_closed` case
   - maybe TCP keep-alive can be turned on to prevent false-positive timeouts when redis is taking too long to respond with data, but is alive
* the slot map should be refreshed when erlang workers related to the old master die
* DB requests should be queued/retried and executed on the new master

Note: I saw that there is a `send_timeout` configuration option (with the 5000ms default?), but that option does not seem to do anything with the forever-hanging TCP connections. Maybe the `{send_timeout_close, true}` flag should be used from gen_tcp as well? Unfortunately it is not really documented in OTP either how these flags behave.

**Comment by e-kmisk** [comment]
Setting raw socket options seems to force the correct behavior we want (unfortunately these are not properly documented in OTP):
```erlang
-define(EREDIS_CLUSTER_SOCKET_OPTS, [
    {nodelay, true},
    %% Enable keep-alive when there is no TCP traffic, to detect dead sockets:
    {keepalive, true},
    %% See Linux kernel file: include/uapi/linux/tcp.h
    %%  - send keep-alive packets after 1s (minimum possible) of no traffic
    %%  - time out after one failed try if the keep-alive is not acknowledged
    %% TCP_KEEPIDLE in seconds - cannot be more granular here:
    {raw, 6, 4, <<1:32/native>>},
    %% TCP_KEEPCNT - try only once, fail fast, better than hanging:
    {raw, 6, 6, <<1:32/native>>},
    %% TCP_KEEPINTVL - probably does not matter when KEEPCNT == 1:
    {raw, 6, 5, <<1:32/native>>},
    %% TCP_USER_TIMEOUT in milliseconds - should be > TCP_KEEPIDLE:
    {raw, 6, 18, <<1100:32/native>>}
]).
```

If you think this should be done then maybe it's worth adding info about these to the documentation? In particular, TCP_USER_TIMEOUT seems pretty necessary to force the socket closing to happen: https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/

Particularly in the "Busy ESTAB socket" scenario, the current behavior (out of the box) doesn't make much sense - it completely negates HA in case of hardware failure, since even if the redis cluster replica takes over, it will not be properly handled and eredis_cluster will keep trying to send requests to the dead master's pool.

**Comment by zuiderkwast** [comment]
Hi @e-kmisk! Thanks for reporting this. I'm curious who you are. Are you working on the SGSN/MME/AMF/PCC products?

As you found out, we don't provide any TCP options by default, so everything has to be provided by the user. So what can we do?

* We could add some TCP options by default, as long as they're backward compatible and doesn't break anyone's setup, e.g. we could set
    * `{nodelay, true}` (we always send full Redis commands),
    * `{keepalive, true}` and
    * `{send_timeout_close, true}`.
* I don't think we should set Linux-specific options by default. We can document them though.
* We could handle `{error, etimedout}`. I don't know exactly when we get this message. Do you?
* Alternatively, we could implement some keepalive mechanism on the Redis level, e.g. periodically sending the PING command. It's not necessary to do it on every connection, just per Redis node.

WDYT?

**Comment by e-kmisk** [comment]
I am working on SBG, my corporate email is kristof.miskolczi@ericsson.com. 

* TCP nodelay is probably not really related to the TR, it just seemed sensible to set for possible latency improvements in our case
* TCP keepalive flag is only really meaningful if the other keepalive related knobs are also tweaked (INTVL, CNT) from their way too large kernel defaults. It seems that Erlang only allows this via those ugly "raw" flags. Additionally, TCP_USER_TIMEOUT is also needed to reduce the 16 minute pending-send scenario to <2 seconds, which also only has a raw option to be set.
* Erlang's `send_timeout_close` is not something I actually tried, as for us the kernel provided functionality (via  keepalive + TCP_USER_TIMEOUT) seemed quite reliable at dropping the dead connections and it seemed better to rely on kernel functionality to close the sockets

> I don't think we should set Linux-specific options by default. We can document them though.

This would already be helpful, in some "strongly recommended on Linux" section maybe.

Imo. a problem is that *by default* right now, such connections will hang forever, or at least for a very long time (according to the above blog, if the sendQ is _not_ empty, after ~16 minutes the connection will die on Linux with default settings, but that is way too long outage for applications to gracefully handle; additionally until the sender is trying to send something on the connection this 16min timer won't even start).

> We could handle {error, etimedout}. I don't know exactly when we get this message. Do you?

I think you can reproduce this issue without kubernetes (where we got it). All that is needed is to sever the connection some other way. According to the blog above, one easy method is via an iptables DROP rule between `redis-server <=> client` after they established their connection. Afterwards, trying to talk to the DB via `eredis_cluster:q/1` or some other command should eventually produce it (I think) as long as that query is directed to the particular redis-server that got disconnected.

> Alternatively, we could implement some keepalive mechanism on the Redis level, e.g. periodically sending the PING command. It's not necessary to do it on every connection, just per Redis node.

This would also be okay actually, maybe even nicer than our solution, because it could be platform agnostic depending on how it's done. Just noting that with the current behavior, normal blocking eredis calls going to the redis-server who is disconnected this way will hang - including "PING" calls, so it may need some special handling.

**Comment by e-kmisk** [comment]
We can close this imo. with the conclusion that it has been documented in 0.8.0 release.
