### ISSUE TITLE
`poolboy` dependency alternatives

### ISSUE THREAD

**Issue by e-kmisk** [Nordix/eredis_cluster#64]
There are some problems with the usage of poolboy in `eredis_cluster`:

* poolboy is not actively maintained, the last code change was more than 5 years ago
* pools towards the same redis server seem to have no merit since redis is single-threaded - sending commands on separate TCP connections still gets serialized somehow. similarly to gRPC connection pooling it only helps with TCP packet loss head-of-line blocking not much else (maybe if the gen_server process would get overwhelmed with messages it could also help, but this is unlikely)
* poolboy adds large overhead on top of using raw `eredis:q` since it
  * makes `erlang:monitor` and `erlang:demonitor` calls for each DB command
  * makes multiple calls to private `ets` tables for each DB command
  * introduces another process that needs to have data copied to/from its message queue

Considering that pooling per server probably doesn't improve the performance, all of the overhead introduced by it is without much if any merit. In raw `eredis_cluster:q` commands/sec measurements, **more than 30% of the CPU load is spent in calls related poolboy**, and only ~66% is spent in `eredis` modules.

Is there some way without major changes to this project to cut out the poolboy middleman, and to instead directly supervise `eredis_client` gen_server processes?

**Comment by zuiderkwast** [comment]
Have a look at ecredis. It's basically eredis_cluster without pools.

**Comment by e-kmisk** [comment]
Thanks, will check that option
