### ISSUE TITLE
new release that includes `eredis` 1.7.0

### ISSUE THREAD

**Issue by e-kmisk** [Nordix/eredis_cluster#65]
Could eredis_cluster be updated to use eredis 1.7.0? Similarly to PR https://github.com/Nordix/eredis_cluster/pull/60

The username/password code examples should be updated in eredis_cluster documents to also use the obfuscated wrappers so that the examples are secure by default.

**Comment by bjosv** [comment]
Sure, it's ongoing. Please review the readme updates in #66.
